[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040 --protocol swd --log-format=oneline --speed=20000"
linker = "flip-link"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
