on: [push, pull_request]
name: Check Code Workflow

jobs:
  check-format:
    name: Check Format Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
          echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
          echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
      - name: Check Formatting
        run: |
          cargo xtask fmt-check
  clippy:
    name: Check Clippy Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
          echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
          echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
      - name: Check Formatting
        run: |
          cargo xtask clippy
